#apiVersion: v1
#kind: Service
#metadata:
#  name: zevrant-gradle-cache-service
#spec:
#  ports:
#    - port: 80
#      targetPort: 5071
#  selector:
#    app: zevrant-gradle-cache-service
#
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zevrant-gradle-cache-service-deployment
#  labels:
#    app: zevrant-gradle-cache-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: zevrant-gradle-cache-service
#  template:
#    metadata:
#      labels:
#        app: zevrant-gradle-cache-service
#    spec:
#      securityContext:
#        runAsUser: 1025648
#        runAsGroup: 1025648
#        fsGroup: 1025648
#      volumes:
#        - name: gradle-cache
#          nfs:
#            server: nfs-controller.zevrant-services.com
#            path: /jenkins/gradle
#      imagePullSecrets:
#        - name: regcred
#      nodeSelector:
#        architecture: amd64
#      containers:
#        - name: zevrant-gradle-cache-service
#          image: gradle/build-cache-node:9.11
#          volumeMounts:
#            - name: gradle-cache
#              mountPath: /data
#          ports:
#            - containerPort: 5071
